(()=>{
const D=window.FIVE_DATA,$=s=>document.querySelector(s),all=[...document.querySelectorAll('.section')];
let challenge=null,index=0,score=0,picked=null,responses=[],studentName='';
const ar=n=>String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[d]);
const key='5x5_progress_v2';
function state(){try{return JSON.parse(localStorage.getItem(key)||'{"completed":[],"log":[]}')}catch{return {completed:[],log:[]}}}
function save(s){localStorage.setItem(key,JSON.stringify(s))}
function show(id){all.forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
function renderJourney(){
 const s=state(),grid=$('#challengeGrid');grid.innerHTML='';
 const done=s.completed.length, total=D.challenges.filter(c=>c.questions.length).length;
 $('#completedCount').textContent=ar(done);$('#questionCount').textContent=ar(s.log.reduce((a,x)=>a+5,0));$('#journeyCount').textContent=`${ar(done)} / ${ar(D.challenges.length)} تحديات`;
 $('#journeyBar').style.width=(done/D.challenges.length*100)+'%';
 D.challenges.forEach((c,i)=>{const unlocked=c.questions.length>0 && (i===0 || s.completed.includes(D.challenges[i-1].id));const finished=s.completed.includes(c.id);const b=document.createElement('button');b.type='button';b.className='challenge '+(finished?'done ':unlocked?'current ':'locked');b.innerHTML=`<span class="challenge-num">${finished?'✓':unlocked?'🔓':'🔒'} ${ar(c.number)}</span><h3>${c.title}</h3><p>${c.subtitle}</p><small>${finished?'مكتمل':unlocked?'ابدئي التحدي':'يفتح بعد إكمال السابق'}</small>`;if(unlocked)b.onclick=()=>start(c);grid.appendChild(b)})
}
function start(c){studentName=($('#studentName').value||studentName||'').trim();if(!studentName){$('#studentName').focus();return}challenge=c;index=0;score=0;responses=[];show('#quiz');renderQuestion()}
function renderQuestion(){const q=challenge.questions[index];picked=null;$('#quizChallenge').textContent=`تحدي ${ar(challenge.number)}`;$('#quizTitle').textContent=challenge.title;$('#progressText').textContent=`${ar(index+1)} / ٥`;$('#progressBar').style.width=((index+1)/5*100)+'%';$('#topic').textContent=q.topic;$('#skill').textContent=q.skill;$('#questionImage').src=q.image;$('#questionImage').alt='السؤال';$('#questionExplanation').textContent=q.explanation||'فكري في القانون أو الفكرة الفيزيائية المرتبطة بالسؤال، ثم اختاري الإجابة الأنسب.';const c=$('#choices');c.innerHTML='';['A','B','C','D'].forEach(l=>{const b=document.createElement('button');b.className='choice';b.textContent=l;b.onclick=()=>{[...c.children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected');picked=l;$('#nextBtn').disabled=false};c.appendChild(b)});$('#nextBtn').disabled=true}
$('#nextBtn').onclick=()=>{const q=challenge.questions[index];responses.push({id:q.id,chosen:picked,correct:q.answer,topic:q.topic,skill:q.skill,explanation:q.explanation});if(picked===q.answer)score++;if(index<4){index++;renderQuestion()}else finish()};
function finish(){const s=state();if(!s.completed.includes(challenge.id))s.completed.push(challenge.id);const now=new Date(),date=now.toLocaleDateString('ar-SA',{year:'numeric',month:'long',day:'numeric'});const code=`5X5-${challenge.number}-${Date.now().toString(36).toUpperCase()}`;s.log.push({name:studentName,challenge:challenge.number,title:challenge.title,score,date,ids:challenge.questions.map(q=>q.id),code});save(s);
 show('#result');$('#scoreNum').textContent=score;$('#studentNameResult').textContent=studentName;$('#challengeNo').textContent=challenge.number;$('#challengeName').textContent=challenge.title;$('#questionIds').textContent=challenge.questions.map(q=>q.id).join(' • ');$('#completionDate').textContent=date;$('#completionCode').textContent=code;$('#scoreLabel').textContent=score===5?'متقنة 🏆':score>=3?'بداية قوية ⭐':'نراجعها معًا 🌷';$('#thanksMain').textContent=score===5?'أداء رائع! واصلي رحلتك نحو الإتقان.':'أحسنتِ على الاستمرار. الخطأ فرصة جديدة للتعلم.';$('#resultMsg').textContent=`أتممتِ تحدي ${challenge.title} بنتيجة ${score} من 5.`;const r=$('#review');r.innerHTML='';responses.forEach((x,i)=>{const d=document.createElement('div');d.className='review-item';d.innerHTML=`السؤال ${ar(i+1)} • ${x.topic} • المهارة: ${x.skill} — إجابتك <b>${x.chosen}</b> | الصحيحة <b>${x.correct}</b><p class="review-tip">💡 ${x.explanation||''}</p> <span class="${x.chosen===x.correct?'ok':'bad'}">${x.chosen===x.correct?'✓ صحيح':'✗ راجعيه'}</span>`;r.appendChild(d)});renderJourney();renderTeacher()}
$('#startBtn').onclick=()=>{studentName=($('#studentName').value||'').trim();if(!studentName){$('#studentName').focus();return}renderJourney();$('#journey').scrollIntoView({behavior:'smooth'})};
$('#aboutBtn').onclick=()=>{ $('#about').classList.remove('hidden');$('#about').scrollIntoView({behavior:'smooth'})};
$('#backBtn').onclick=()=>{show('#journey');renderJourney()};$('#nextChallengeBtn').onclick=()=>{show('#journey');renderJourney()};$('#printBtn').onclick=()=>window.print();
$('#teacherBtn').onclick=()=>{show('#teacherPanel');renderTeacher()};$('#closeTeacher').onclick=()=>{show('#journey');renderJourney()};
$('#exportBtn').onclick=()=>{const s=state();const blob=new Blob([JSON.stringify(s.log,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='5x5-سجل-الإنجاز.json';a.click();URL.revokeObjectURL(a.href)};
$('#resetBtn').onclick=()=>{if(confirm('هل تريدين مسح سجل هذا الجهاز؟')){localStorage.removeItem(key);renderJourney();renderTeacher()}};
function renderTeacher(){const s=state();$('#tStudents').textContent=ar(new Set(s.log.map(x=>x.name)).size);$('#tAttempts').textContent=ar(s.log.length);$('#tQuestions').textContent=ar(s.log.length*5);$('#tAverage').textContent=(s.log.length?Math.round(s.log.reduce((a,x)=>a+x.score,0)/(s.log.length*5)*100):0)+'٪';$('#teacherChallenges').innerHTML=D.challenges.map(c=>{const n=s.log.filter(x=>x.challenge===c.number).length;return `<div class="teacher-row"><b>تحدي ${ar(c.number)}</b><span>${c.title}</span><em>${ar(n)} إنجاز</em></div>`}).join('');$('#teacherLog').innerHTML=s.log.slice(-8).reverse().map(x=>`<div class="teacher-row"><b>${x.name}</b><span>تحدي ${ar(x.challenge)} — ${x.title}</span><em>${ar(x.score)}/٥</em></div>`).join('')||'<p>لا توجد إنجازات بعد.</p>'}
renderJourney();renderTeacher();
})();
